version: '3.3'
services:
  briana-customer:
    image: ttre16/briana-customer:latest
    env_file:
      - briana.env
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 256M
    networks:
      - briana_api
networks:
  briana_api:
    external: true
