---
- name: Init a new Swarm cluster
  docker_swarm:
    state: present
  register: swarm_cluster_info

- name: Add leader label
  docker_node:
    hostname: "{{ ansible_hostname }}"
    labels:
      role: leader

- name: Create docker networks
  docker_network:
    name: "{{ item }}"
    driver: overlay
  loop:
    - briana_net
    - btiana_api
