---
 - name: Add Docker GPG apt Key
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

 - name: Add Docker Repository
   apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present

 - name: Install required packages
   apt:
     name:
       - python3-pip
       - python3-setuptools
       - docker-ce
     state: latest
     update_cache: yes

 - name: Install required docker modules for Python
   pip:
     name:
       - docker
       - jsondiff
