name: Build image, push it to Docker Hub and dispatch rolling update action.
env:
  DH_REPO_NAME       : "ttre16/${{ github.event.client_payload.repo_name }}"
  SERVICE_NAME       : "${{ github.event.client_payload.service_name }}"
  IMAGE_TAG          : "${{ github.event.client_payload.commit_hash }}"
  IMAGE_NAME         : "ttre16/${{ github.event.client_payload.repo_name }}:${{ github.event.client_payload.commit_hash }}"
  CHECKOUT_REPO_NAME : "briana-crm/${{ github.event.client_payload.repo_name }}"
  DISPATCH_REPO      : "briana-crm/briana-deploy"
  UPDATE_EVENT_TYPE  : "rolling_update"

on:
  repository_dispatch:
    types: [delivery]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.CHECKOUT_REPO_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DH_REPO_NAME }}
          tags: ${{ env.IMAGE_TAG }},latest

  dispatch:
    name: Dispatch rolling update action
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ env.DISPATCH_REPO }}
          event-type: ${{ env.UPDATE_EVENT_TYPE }}
          client-payload: '{"service_name": "${{ env.SERVICE_NAME }}", "image_name": "${{ env.IMAGE_NAME }}" }'
