name: Deploy new docker stack

on:
  workflow_dispatch:
    inputs:
      compose_file:
        description: 'Docker compose filename'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy docker stack with Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: docker-swarm-cluster/main.yml
          inventory: docker-swarm-cluster/hosts.txt
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          extra_vars: compose_file=${{ github.event.inputs.compose_file }}
          ssh_common_args: StrictHostKeyChecking=no 
          tags: deploy
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
