name: Rolling update

on:
  repository_dispatch:
    types: [push_candidate]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update service with Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: docker-swarm-cluster/main.yml
          inventory: docker-swarm-cluster/hosts.yml
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          extra_vars: |
            service_name=${{ github.event.client_payload.service }}
            image_name=${{ github.event.client_payload.image }}
          tags: update
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
